-- =========================================
-- SUPERSTORE SALES ANALYSIS
-- Tool: MySQL
-- Objective: Explore revenue, profitability, customer behavior,
-- and product performance using SQL.
-- =========================================

-- Select the working database schema
USE week11_superstore;

-- Check initial row count after import to confirm dataset loaded correctly
SELECT COUNT(*)
FROM superstore_data;

-- =========================================
-- CLEAN COLUMN NAMES
-- Rename columns to remove spaces and convert to snake_case
-- This improves readability and simplifies SQL queries
-- =========================================

ALTER TABLE superstore_data
RENAME COLUMN `Row ID` TO row_id,
RENAME COLUMN `Order ID` TO order_id,
RENAME COLUMN `Order Date` TO order_date,
RENAME COLUMN `Ship Date` TO ship_date,
RENAME COLUMN `Ship Mode` TO ship_mode,
RENAME COLUMN `Customer ID` TO customer_id,
RENAME COLUMN `Customer Name` TO customer_name,
RENAME COLUMN `Postal Code` TO postal_code,
RENAME COLUMN `Product ID` TO product_id,
RENAME COLUMN `Sub-Category` TO sub_category,
RENAME COLUMN `Product Name` TO product_name,
RENAME COLUMN `Segment` TO segment,
RENAME COLUMN `Country` TO country,
RENAME COLUMN `Profit` TO profit,
RENAME COLUMN `City` TO city,
RENAME COLUMN `State` TO state,
RENAME COLUMN `Region` TO region,
RENAME COLUMN `Category` TO category,
RENAME COLUMN `Sales` TO sales,
RENAME COLUMN `Quantity` TO quantity,
RENAME COLUMN `Discount` TO discount;

-- =========================================
-- VALIDATE DATE FORMAT
-- Preview how STR_TO_DATE converts the text dates
-- =========================================

SELECT order_date,
STR_TO_DATE(order_date,'%d-%m-%Y')
FROM superstore_data;

-- Disable safe updates temporarily to allow full-table updates
SET SQL_SAFE_UPDATES = 0;

-- =========================================
-- CONVERT DATE VALUES
-- Convert text date columns to proper date format
-- =========================================

Update superstore_data
set order_date = str_to_date(order_date, '%d-%m-%Y');

Update superstore_data
set ship_date = str_to_date(ship_date, '%d-%m-%Y');

-- Modify column datatype from TEXT to DATE
Alter table superstore_data
Modify order_date DATE,
Modify ship_date DATE;

-- =========================================
-- QUICK DATA PREVIEW
-- Inspect product sales values before converting numeric columns
-- =========================================

Select product_name, sales
FROM superstore_data
limit 40;

-- =========================================
-- CONVERT NUMERIC COLUMNS
-- Change numeric fields from TEXT to appropriate numeric datatypes
-- =========================================

ALTER TABLE superstore_data
MODIFY sales DOUBLE,
MODIFY quantity INT,
MODIFY discount DOUBLE,
MODIFY profit DOUBLE;

-- Postal codes are stored as text to preserve leading zeros
ALTER TABLE superstore_data
MODIFY postal_code VARCHAR(20);

-- Restore safe update protection after completing data transformations
SET SQL_SAFE_UPDATES = 1;

-- =========================================
-- VERIFY TABLE STRUCTURE
-- Confirm column names and data types
-- =========================================

Describe Superstore_data;

-- =========================================
-- BASIC DATA INSPECTION
-- View a sample of records to ensure data looks correct
-- =========================================

SELECT *
FROM superstore_data
LIMIT 10;

-- =========================================
-- DATASET VALIDATION CHECKS
-- Ensure data integrity before analysis
-- =========================================

-- Confirm row count
SELECT COUNT(*)
FROM superstore_data;

-- Verify date range of dataset
SELECT 
MIN(order_date),
MAX(order_date)
FROM superstore_data;

-- Count unique customers
SELECT COUNT(DISTINCT customer_id)
FROM superstore_data;

-- Check for missing order dates
Select 
count(*) - count(order_date) as missing_dates
FROM superstore_data;

-- Count unique products
SELECT COUNT(DISTINCT product_name)
FROM superstore_data;

-- View distinct regions present in the dataset
SELECT DISTINCT region FROM superstore_data;

-- =========================================
-- FOUNDATION BUSINESS QUERIES
-- Initial exploratory analysis to understand
-- revenue, profitability, customer value,
-- and product performance.
-- =========================================

-- Analyze total revenue generated by each region
-- Helps identify which geographic markets drive the most sales
select region, 
	Round(Sum(sales), 2) as total_revenue
from superstore_data
group by region
order by total_revenue desc;

-- Analyze total profit generated by each region
-- Allows comparison of profitability across geographic markets
select region, 
	Round(Sum(profit), 2) as total_profit
from superstore_data
group by region
order by total_profit desc;

-- Compare revenue and profit together by region
-- Helps determine whether high revenue regions are also profitable
select region, 
	Round(Sum(sales), 2) as total_revenue,
    Round(Sum(profit), 2) as total_profit	
from superstore_data
group by region
order by total_revenue desc;

-- Calculate profit margin by region
-- Profit margin = profit ÷ revenue
-- Used to identify efficiency and profitability differences between regions
select region, 
	Round(Sum(sales), 2) as total_revenue,
    ROUND((SUM(profit) / SUM(sales)) * 100, 2) AS profit_margin	
from superstore_data
group by region
order by profit_margin desc;

-- Evaluate revenue and profit contribution of each customer segment
-- Segments represent different types of customers (Consumer, Corporate, Home Office)
select segment, 
	Round(Sum(sales), 2) as total_revenue,
    Round(Sum(profit), 2) as total_profit	
from superstore_data
group by segment
order by total_revenue desc;

-- Calculate profit margin by segment
-- Helps identify which customer segment generates the most efficient profits
select segment, 
	Round(Sum(sales), 2) as total_revenue,
    Round(Sum(profit) / sum(sales) *100 , 2) as profit_margin	
from superstore_data
group by segment
order by profit_margin desc;

-- Identify the top 10 customers by total sales
-- Helps reveal high-value customers who contribute the most revenue
SELECT
	customer_id,
	customer_name,
	Round(SUM(sales) ,2) AS total_sales
FROM superstore_data
GROUP BY customer_id, customer_name
ORDER BY total_sales DESC
Limit 10;

-- Calculate total revenue generated by each product category
-- Used to understand which product groups drive business sales
SELECT
	category,
	Round(SUM(sales) ,2) AS total_sales
FROM superstore_data
GROUP BY category
ORDER BY total_sales DESC;

-- Calculate profit margin by product category
-- Helps evaluate which product categories are most profitable
SELECT
	category,
	Round(SUM(sales) ,2) AS total_sales,
    Round(sum(profit) / sum(sales) *100 ,2) as profit_margin
FROM superstore_data
GROUP BY category
ORDER BY profit_margin DESC;

-- Identify products that generate overall losses
-- HAVING clause filters products where total profit is negative
-- Useful for detecting pricing issues or unprofitable items
Select
	product_id,
	product_name,
    category,
    Round(Sum(profit) ,2) as total_loss
from superstore_data
group by product_id, product_name, category
HAVING SUM(profit) < 0
order by total_loss asc
limit 10;

-- =========================================
-- ANALYTICAL OBSERVATIONS
-- =========================================

-- The West region generates the highest overall revenue and profit,
-- indicating it is the strongest geographic market for the business.

-- The Central region produces moderate revenue but significantly lower
-- profitability, suggesting potential operational inefficiencies or
-- higher discounting in this region.

-- Among customer segments, the Consumer segment contributes the highest
-- total revenue, while the Home Office segment generates the lowest
-- revenue but achieves the highest profit margin.

-- Technology is the top-performing product category, delivering both
-- the highest revenue and the strongest profit margins.

-- Furniture generates relatively high revenue but an extremely low
-- profit margin (~2.5%), suggesting potential pricing, discounting,
-- or cost management issues.

-- Several individual products generate significant negative profit,
-- highlighting opportunities for pricing review or product portfolio
-- optimization.

-- A small group of high-value customers contributes a significant
-- share of total revenue, suggesting potential opportunities for
-- targeted retention or loyalty strategies.

-- =========================================
-- SELF JOIN ANALYSIS
-- Identify clusters of high-value customers located in the same city.
-- The query first selects the top 50 customers by total sales and then
-- performs a self join to pair customers who operate within the same city.
-- This helps reveal geographic concentrations of important clients.
-- =========================================


SELECT
    a.customer_id as customer_1,
	a.customer_name AS name_1,
    b.customer_id AS customer_2,
    b.customer_name AS name_2,
    a.city
FROM
(
	-- Subquery A: Select the top 50 customers by total sales
    -- GROUP BY ensures each customer appears once
    SELECT customer_id, customer_name, city
    FROM superstore_data
    GROUP BY customer_id, customer_name, city
    ORDER BY SUM(sales) DESC
    LIMIT 50
) a
JOIN
(
	-- Subquery B: Same top 50 customers used again to compare customers
    -- against each other within the same city
    SELECT customer_id, customer_name, city
    FROM superstore_data
    GROUP BY customer_id, customer_name, city
    ORDER BY SUM(sales) DESC
    LIMIT 50
) b
ON a.city = b.city
AND a.customer_id < b.customer_id;

-- The condition a.customer_id < b.customer_id prevents:
-- 1. matching a customer with themselves
-- 2. duplicate pairs such as (A,B) and (B,A)

-- =========================================
-- CTE REWRITE PRACTICE
-- Rewriting the previous self join using a Common Table Expression (CTE).
-- This approach improves readability and avoids repeating the same
-- subquery multiple times.
-- =========================================

With top_customers AS (
	select
		customer_id,
        customer_name,
        city,
        Round(sum(sales) ,2) as total_sales
	from superstore_data
    Group by customer_id, customer_name, city
    Order by total_sales DESC
    Limit 50
)
Select
	a.customer_id as customer_1,
	a.customer_name AS name_1,
    b.customer_id AS customer_2,
    b.customer_name AS name_2,
    a.city
From top_customers a
Join top_customers b
On a.city = b.city
And a.customer_id < b.customer_id;

-- This CTE version performs the same analysis as SELF JOIN ANALYSIS,
-- but structures the logic more clearly by defining the
-- "top_customers" dataset once and reusing it in the join.

-- =========================================
-- OBSERVATION
-- =========================================
-- Some cities (notably New York City) contain multiple high-value customers,
-- suggesting strong geographic clusters of important clients.
-- Such clusters may represent key regional markets for targeted sales strategies.



-- =========================================
-- ADVANCED ANALYTICAL QUERIES
-- Implementing analytical SQL patterns to
-- extract deeper business insights.
-- =========================================

-- Identify customers whose total sales exceed
-- the average sales generated by all customers.
-- The inner subquery calculates total sales per customer,
-- then compares each customer's sales with the overall average.

Select
		customer_id,
        customer_name,
        Round(sum(sales) ,2) as total_sales
From	
		superstore_data
Group by
		customer_id,
        customer_name
Having 
		Sum(sales) > (
        Select 
				Avg (customer_sales)
		From (
				Select sum(sales) as customer_sales
                From superstore_data
                Group by customer_id
			)t
)
order by
		total_sales Desc;

-- Identify products generating higher-than-average profit.
-- The query aggregates profit per product and filters only
-- those products whose total profit exceeds the average
-- profit generated by all products.

Select
		product_id,
        product_name,
        Round(sum(profit) ,2) as total_profit
From	
		superstore_data
Group by
		product_id,
        product_name
Having 
		Sum(profit) > (
        Select 
				Avg (product_profit)
		From (
				Select sum(profit) as product_profit
                From superstore_data
                Group by product_id
			)t
)
order by
		total_profit Desc;
  
-- Rewrite the above customer sales query using CTEs.
-- The first CTE calculates total sales for each customer,
-- while the second CTE calculates the average sales across customers.

With customer_sales As (
		Select
			customer_id,
            customer_name,
            Sum(sales) as total_sales
		From
			superstore_data
		group by
			customer_id,
            customer_name
),
	average_sales As (
		Select
			avg(total_sales) as avg_sales
		From
			customer_sales
)
Select
	customer_id,
	customer_name,
    Round(total_sales, 2) As total_sales
From
	customer_sales
Where
	total_sales > (Select avg_sales from average_sales)
ORDER BY 
	total_sales DESC;
    
-- Rewrite the above product profitability query using CTEs.
-- This improves query readability by separating calculation
-- of product profits and average profit into logical layers.
With product_profit As (
	Select
		product_id,
        product_name,
        Sum(profit) as total_profit
	From
		superstore_data
	Group by
		product_id,
        product_name
),
average_profit AS(
	Select
		Avg(total_profit) as avg_profit
	From
		product_profit
)
Select
	product_id,
	product_name,
    Round(total_profit ,2) as total_profit
From
	product_profit
Where 
	total_profit > (select avg_profit from average_profit)
Order by
	total_profit Desc;
   
-- Calculate monthly revenue and profit by aggregating
-- sales and profit for each year-month combination.
-- This enables time-series analysis of business performance.

With monthly_sales As(
	select
		year(order_date) as year,
        Month(order_date) as month,
        sum(sales) as monthly_revenue,
        sum(profit) as monthly_profit
	From
		superstore_data
	Group by 
		year(order_date), Month(order_date)
)
Select
	year,
    month,
    Round(monthly_revenue, 2) as monthly_revenue,
    Round(monthly_profit, 2) as monthly_profit
from
	monthly_sales
Order by
	year, month;
    
-- Monthly performance dataset used for multiple analyses
-- including revenue trends, profitability patterns,
-- top-performing months, and loss-making periods.
  
-- Identify the top 10 months generating the highest profit.
-- Useful for detecting seasonal profitability peaks.

With monthly_sales As(
	select
		year(order_date) as year,
        Month(order_date) as month,
        sum(sales) as monthly_revenue,
        sum(profit) as monthly_profit
	From
		superstore_data
	Group by 
		year(order_date), Month(order_date)
)
Select
	year,
    month,
    Round(monthly_revenue, 2) as monthly_revenue,
    Round(monthly_profit, 2) as monthly_profit
from
	monthly_sales
Order by
	monthly_profit DESC
    Limit 10;
    
-- Identify the top 10 months generating the highest revenue.

    With monthly_sales As(
	select
		year(order_date) as year,
        Month(order_date) as month,
        sum(sales) as monthly_revenue,
        sum(profit) as monthly_profit
	From
		superstore_data
	Group by 
		year(order_date), Month(order_date)
)
Select
	year,
    month,
    Round(monthly_revenue, 2) as monthly_revenue,
    Round(monthly_profit, 2) as monthly_profit
from
	monthly_sales
Order by
	monthly_revenue DESC
    Limit 10;
  
-- Identify months where total profit was negative.
-- These months may indicate heavy discounting,
-- operational inefficiencies, or cost spikes.

    With monthly_sales As(
	select
		year(order_date) as year,
        Month(order_date) as month,
        sum(sales) as monthly_revenue,
        sum(profit) as monthly_profit
	From
		superstore_data
	Group by 
		year(order_date), Month(order_date)
)
Select
	year,
    month,
    Round(monthly_revenue, 2) as monthly_revenue,
    Round(monthly_profit, 2) as monthly_profit
from
	monthly_sales
Where
	monthly_profit < 0
Order by
	monthly_profit ASC;

-- Identify the least profitable months overall.

With monthly_sales As(
	select
		year(order_date) as year,
        Month(order_date) as month,
        sum(sales) as monthly_revenue,
        sum(profit) as monthly_profit
	From
		superstore_data
	Group by 
		year(order_date), Month(order_date)
)
Select
	year,
    month,
    Round(monthly_revenue, 2) as monthly_revenue,
    Round(monthly_profit, 2) as monthly_profit
from
	monthly_sales
Order by
	monthly_profit ASC
Limit 10;

-- Aggregate revenue and profit by quarter to
-- analyze seasonal performance trends.

Select
	Year(order_date) as year,
    Quarter(order_date) as quarter,
    ROUND(SUM(sales),2) AS quarterly_revenue,
	ROUND(SUM(profit),2) AS quarterly_profit
From 
	superstore_data
Group by 
	Year(order_date),
    Quarter(order_date)
Order by
	year, quarter;
    
-- Calculate average revenue and profit for each quarter
-- across all years to detect consistent seasonal patterns.

WITH quarterly_sales AS (
	SELECT
		YEAR(order_date) AS year,
		QUARTER(order_date) AS quarter,
		SUM(sales) AS quarterly_revenue,
		SUM(profit) AS quarterly_profit
	FROM superstore_data
	GROUP BY YEAR(order_date), QUARTER(order_date)
)

SELECT
	quarter,
	ROUND(AVG(quarterly_revenue),2) AS avg_quarterly_revenue,
	ROUND(AVG(quarterly_profit),2) AS avg_quarterly_profit
FROM quarterly_sales
GROUP BY quarter
ORDER BY quarter;

-- Analyze yearly revenue and profit trends.

Select
	Year(order_date) as year,
    Round(sum(sales) ,2) as total_revenue,
    Round(sum(profit) ,2) as total_profit
From
	superstore_data
Group by
	Year(order_date)
Order by
	year;
    
-- Measure logistics efficiency by calculating
-- the average number of days taken to ship orders
-- for each shipping mode.

SELECT
	ship_mode,
	ROUND(AVG(DATEDIFF(ship_date, order_date)),2) AS avg_shipping_days
FROM superstore_data
GROUP BY ship_mode
ORDER BY avg_shipping_days;

-- Compare shipping speed with profitability
-- by showing both average shipping time and
-- total profit generated by each shipping mode.

SELECT
	ship_mode,
	ROUND(AVG(DATEDIFF(ship_date, order_date)),2) AS avg_shipping_days,
    Round(Sum(profit) ,2) as total_profit
FROM 
	superstore_data
GROUP BY 
	ship_mode
ORDER BY 
	total_profit desc;
  
-- Calculate monthly profit margin to evaluate
-- profitability efficiency over time.

WITH monthly_sales AS (
	SELECT
		YEAR(order_date) AS year,
		MONTH(order_date) AS month,
		SUM(sales) AS monthly_revenue,
		SUM(profit) AS monthly_profit
	FROM superstore_data
	GROUP BY YEAR(order_date), MONTH(order_date)
)

SELECT
	year,
	month,
	ROUND(monthly_revenue,2) AS revenue,
	ROUND(monthly_profit,2) AS profit,
	ROUND((monthly_profit / monthly_revenue) * 100,2) AS profit_margin
FROM monthly_sales
ORDER BY year, month;

-- =========================================
-- ANALYTICAL OBSERVATIONS
-- =========================================

-- The fourth quarter consistently generates the highest revenue
-- and profit across years, indicating strong seasonal demand
-- during the end-of-year period.

-- The first quarter shows the lowest revenue and profitability,
-- suggesting weaker sales momentum early in the year.

-- Standard Class shipping generates the highest total profit,
-- despite having the longest average shipping time (~5 days),
-- indicating that customers are willing to accept slower
-- delivery for lower shipping costs.

-- Faster shipping modes such as Same Day and First Class
-- provide significantly quicker delivery but contribute
-- much lower total profit.

-- Yearly revenue shows an overall upward trend across the dataset,
-- with only a minor dip in 2015 before continuing to grow.

-- Profit follows a similar pattern, showing consistent
-- improvement year over year, indicating healthy business growth.

-- Some individual months show negative profitability,
-- suggesting potential heavy discounting or high costs
-- during those periods.

-- Peak revenue and profit months are heavily concentrated
-- in late-year months (Q4), reinforcing the importance
-- of seasonal sales cycles.

-- =========================================
-- WINDOW FUNCTION ANALYSIS
-- Applying ranking, lag/lead comparisons,
-- and rolling metrics to analyze business trends
-- =========================================

-- Rank products by total sales within each region.
-- The RANK() window function resets ranking for every region
-- using PARTITION BY, allowing comparison of product performance
-- across different geographic markets.

Select
	region,
    product_name,
    Round(sum(sales),0) as total_sales,
    Rank() over (
		partition by region
        order by sum(sales) desc
	) as sales_rank
From
	superstore_data
Group by
	region, product_name;

-- Identify the top 5 best-selling products within each region.
-- The ranking logic is first calculated in a CTE and then filtered
-- to return only the highest-performing products.

With ranked_products As (
	Select
		region,
		product_name,
		Round(sum(sales),0) as total_sales,
		Rank() over (
			partition by region
			order by sum(sales) desc
	) as sales_rank
From
	superstore_data
Group by
	region, product_name
)
Select
	region,
    product_name,
    total_sales,
    sales_rank
From
	ranked_products
where
	sales_rank <= 5
Order by
	region, sales_rank;

-- Calculate month-over-month revenue change using LAG().
-- LAG retrieves revenue from the previous month, allowing
-- calculation of revenue growth or decline over time.

WITH monthly_sales AS (
    SELECT
        YEAR(order_date) AS year,
        MONTH(order_date) AS month,
        Round(SUM(sales),0) AS monthly_revenue
    FROM superstore_data
    GROUP BY YEAR(order_date), MONTH(order_date)
)
SELECT
    year,
    month,
    monthly_revenue,
    Lag(monthly_revenue) Over(
		order by year, month
	) as previous_month_revenue,
    monthly_revenue - Lag(monthly_revenue) over(
		order by year, month
	) As revenue_change
From monthly_sales;

-- Calculate rolling 3-month revenue using a window frame.
-- The query sums revenue for the current month and the
-- previous two months to smooth short-term fluctuations
-- and reveal broader revenue trends.

WITH monthly_sales AS (
    SELECT
        YEAR(order_date) AS year,
        MONTH(order_date) AS month,
        Round(SUM(sales),0) AS monthly_revenue
    FROM superstore_data
    GROUP BY YEAR(order_date), MONTH(order_date)
)
SELECT
    year,
    month,
    monthly_revenue,
    SUM(monthly_revenue) OVER (
        ORDER BY year, month
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS rolling_3_month_revenue
FROM monthly_sales;
    
-- Identify the top-selling product for each month.
-- ROW_NUMBER assigns a unique rank per month based on sales,
-- ensuring exactly one top product per month is returned.

With monthly_product_sales As(
	Select
		Year(order_date) as year,
        Month(order_date) as month,
        product_name,
        Round(sum(sales),0) as total_sales
	From superstore_data
    group by 
		Year(order_date), 
        Month(order_date), 
        product_name
)
select *
from (
	Select
		year,
        month,
		product_name,
		total_sales,
        Row_number() over (
			Partition by year, month
            order by total_sales desc
            ) as sales_rank
		From monthly_product_sales
) as ranked_products
Where sales_rank = 1;

-- Identify the highest revenue-generating product within each region
-- and compare its profitability ranking. This highlights cases where
-- high sales do not necessarily correspond to high profit.
            
SELECT *
FROM (
    SELECT
        region,
        product_name,
        Round(SUM(sales),0) AS total_sales,
        Round(SUM(profit),0) AS total_profit,

        RANK() OVER (
            PARTITION BY region
            ORDER BY Round(SUM(sales),0) DESC
        ) AS sales_rank,

        RANK() OVER (
            PARTITION BY region
            ORDER BY Round(SUM(profit),0) DESC
        ) AS profit_rank
    FROM superstore_data
    GROUP BY region, product_name
) ranked_products
WHERE sales_rank = 1;
    
-- Identify the top-selling product per region for each year.
-- This reveals how product leadership changes over time
-- within different geographic markets.

SELECT *
FROM (
    SELECT
        region,
        Year(order_date) as year,
        product_name,
        Round(SUM(sales),0) AS total_sales,
        Round(SUM(profit),0) AS total_profit,

        RANK() OVER (
            PARTITION BY region, Year(order_date)
            ORDER BY Round(SUM(sales),0) DESC
        ) AS sales_rank,

        RANK() OVER (
            PARTITION BY region, Year(order_date)
            ORDER BY Round(SUM(profit),0) DESC
        ) AS profit_rank

    FROM superstore_data
    GROUP BY region, Year(order_date), product_name
) ranked_products
WHERE sales_rank = 1;

-- Identify the most profitable product in each region
-- and compare its sales ranking. This highlights products
-- that generate strong profit even if they are not top sellers.

SELECT *
FROM (
    SELECT
        region,
        product_name,
        Round(SUM(sales),0) AS total_sales,
        Round(SUM(profit),0) AS total_profit,

        RANK() OVER (
            PARTITION BY region
            ORDER BY Round(SUM(profit),0) DESC
        ) AS profit_rank,
        
        RANK() OVER (
            PARTITION BY region
            ORDER BY Round(SUM(sales),0) DESC
        ) AS sales_rank
    FROM superstore_data
    GROUP BY region, product_name
) ranked_products
WHERE profit_rank = 1;

-- Identify the most profitable product within each region
-- for each year to analyze how profitability leadership
-- evolves over time.

SELECT *
FROM (
    SELECT
        region,
        Year(order_date) as year,
        product_name,
        Round(SUM(sales),0) AS total_sales,
        Round(SUM(profit),0) AS total_profit,

        RANK() OVER (
            PARTITION BY region, Year(order_date)
            ORDER BY Round(SUM(profit),0) DESC
        ) AS profit_rank,
        
        RANK() OVER (
            PARTITION BY region, Year(order_date)
            ORDER BY Round(SUM(sales),0) DESC
        ) AS sales_rank
    FROM superstore_data
    GROUP BY region, Year(order_date), product_name
) ranked_products
WHERE profit_rank = 1;

-- Analyze month-over-month changes in profit using LAG().
-- This highlights periods where profitability improved
-- or declined compared to the previous month.

WITH monthly_profit AS (
    SELECT
        YEAR(order_date) AS year,
        MONTH(order_date) AS month,
        Round(SUM(profit),0) AS monthly_profit
    FROM superstore_data
    GROUP BY YEAR(order_date), MONTH(order_date)
)
SELECT
    year,
    month,
    monthly_profit,
    LAG(monthly_profit) OVER (
        ORDER BY year, month
    ) AS previous_profit,
    monthly_profit - LAG(monthly_profit) OVER (
        ORDER BY year, month
    ) AS profit_change
FROM monthly_profit;

-- High-performing products vary significantly across regions and years,
-- indicating that product demand is geographically and temporally dynamic.
-- Additionally, several products generate strong revenue but weak or
-- negative profit margins, highlighting the importance of analyzing
-- profitability alongside sales performance when making business decisions.